// Elabore que muestre cual es el promedio de las edades de los aprendices de la ficha y cuantos son mayores de edad

function edades (cnt){
    let contador18;
    contador18 = 0;
    let contador;
    contador = 0;
    let edad= parseIntpromt("Ingrese la edad ");
  for (i=0 , i = cnt ,i++) {
    if (edad = 18){
        contador18 = contador18 + 1;
    } else {
        contador = contador + 1;
    }
        
  }
    return contador, contador18;

}


